services:
  bot:
    build:
      context: .
    platform: linux/amd64 # line for building on arm processors
    volumes:
      - .env:/app/.env
    image: docker.hapimeets.com/smartist_taiga/bot:latest
    command: "python -m bot_interface"

  notification_listener:
    build:
      context: .
    platform: linux/amd64
    volumes:
      - .env:/app/.env
    image: docker.hapimeets.com/smartist_taiga/bot:latest
    command: "python -m notification_listener"
    restart: always

  redis:
    image: redis:latest
    restart: always

