services:
  # base:
  #   build:
  #     context: .
  #     target: base
  #   platform: linux/arm64 # line for building on arm processors
  #   image: docker.hapimeets.com/smartist_taiga/base:latest

  bot:
    build:
      context: .
      target: prod
    platform: linux/amd64 # line for building on arm processors
    volumes:
      - .env:/app/.env
    image: docker.hapimeets.com/smartist_taiga/bot:latest
    command: "python -m bot_interface"

  redis:
    image: redis:latest
    restart: always
